version: '3.9'
services:
  es01:
    build: .
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
    deploy:
      restart_policy:
        condition: on-failure
  es02:
    build: .
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    depends_on:
      - es01
    networks:
      - esnet
    deploy:
      restart_policy:
        condition: on-failure
  es03:
    build: .
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    depends_on:
      - es01
    networks:
      - esnet
    deploy:
      restart_policy:
        condition: on-failure
  kibana:
    build:
      context: ./kibana
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - elasticsearch.username="kibana_system"
      - elasticsearch.password=123456
      - xpack.security.session.idleTimeout="1h"
      - xpack.security.session.lifespan="30d"
    ports:
      - 5601:5601
    depends_on:
      - es01
    networks:
      - esnet
volumes:
  esdata:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
networks:
  esnet: